---
variables:
  GIT_DEPTH: "1"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"

stages:
  - molecule

molecule:
  stage: molecule
  tags:
    - shell
  script:
    - echo $CI_COMMIT_DESCRIPTION
    - cd playbooks/roles/$CI_COMMIT_TAG/ && molecule test
