---
variables:
  GIT_DEPTH: "1"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"

stages:
  - molecule

molecule:
  stage: molecule
  tags:
    - shel
  script:
    - |
      cd playbooks/roles/
      if [[ ! -z "$CI_COMMIT_DESCRIPTION" ]]; then
        cd $CI_COMMIT_DESCRIPTION/ && molecule test
      else
        for role in `find . -type d -name "molecule" | cut -d'/' -f 2`; do
          cd $role && molecule test
          cd ..
        done
      fi
