---
# tasks file for basic

- name: install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - haveged
    - chrony
    - vim
 
- name: start and enable required services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - haveged
    - chrony
