---
# tasks file for basic

- name: install epel-repo
  yum:
    name:
      - epel-release
    state: present

- name: install required packages
  yum:
    name:
      - haveged
      - chrony
      - vim
    state: present

- name: start and enable required services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - haveged
    - chronyd
